version: '1.0'
services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    image: anna099/tdipp4
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=chat2
    volumes:
      - .:/public
    ports:
      - "49161:3000"
    container_name: cloned-tidpp-app

  mysql:
    image: mysql:5.7
    networks:
        - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=chat2
    container_name: cloned-tidpp-mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "49162:80"
    environment:
      - PMA_HOST=cloned-tidpp-app
      - PMA_PORT=4320
    volumes:
      - /sessions
    container_name: cloned-tidpp-phpmyadmin

networks:
  frontend:
  backend:
